"""Real durable journals/bundles, with explicitly synthetic game evidence.

No GPU, language call, dataset or real game is generated by these tests.
"""
import ast
from copy import deepcopy
from dataclasses import replace
import json
from pathlib import Path
import subprocess
import sys
from contextlib import nullcontext
from types import ModuleType
from types import SimpleNamespace

import pytest

from tests.canonical_collection.test_game_bundle import _fixture, _plan
from tests.phase2.test_probe_policy_runner import runtime
from tests.phase2.test_decision_opportunity import Mapper, q_matrix
from werewolf.artifact_io import canonical_json_bytes, publish_artifact, read_artifact_file
from werewolf.canonical_collection.attempt_ledger import collection_plan_from_record
from werewolf.canonical_collection.game_bundle import _raw_public_event, publish_canonical_game_bundle
from werewolf.canonical_collection.trajectory_evidence import construct_private_replay_evidence
from werewolf.canonical_collection.failure_evidence import construct_canonical_partial_evidence, publish_canonical_partial_evidence
from werewolf.phase2_gameplay import (
    GameplayLedger, NAMES, allocations, derived_seed, digest, freeze_source, make_plan,
    policy_for, publish_campaign, recover, validate_plan, validate_publication, verify_results,
)
from werewolf import phase2_gameplay_server as server
from scripts import phase2_gameplay_campaign as cli


def plan(n=2, purpose="qualification", *, paths=None, gate=None):
    source = {"commit": "a" * 40, "branch": "twd/mainline", "tracked_worktree_clean": True,
              "staged_tracked_changes": False, "source_sha256": {"fixture.py": "b" * 64}}
    game = _plan(collection_id=NAMES[purpose], ordered_seed_pool=tuple(range(100, 100 + n)),
                 target_canonical_success_count=n, source_revision=source["commit"])
    profile = {"schema_version": "phase2_router_gameplay_v1", "purpose": purpose, "campaign_id": NAMES[purpose],
        "randomized_games": n, "planning_status": "FROZEN", "qualification": None, "qualification_gate": gate,
        "paths": paths or {"plan": "/fixture/plan", "work": "/fixture/work", "destination": "/fixture/pub"},
        "excluded_game_plans": []}
    return make_plan(purpose=purpose, game_plan=game, source=source, runtime_inputs={}, exclusions=[],
                     campaign_profile=profile, qualification_gate=gate)


def no_router(*args):
    return {"triggered": False, "t1_committed": False, "t3_committed": False}


def bundle(ledger, allocation, claim, winner="Werewolf"):
    game = collection_plan_from_record(ledger.plan["game_plan"])
    _, _, evidence, replay = _fixture(game, claim, game_id=allocation["game_id"])
    old = evidence.private_replay_evidence
    private = construct_private_replay_evidence(game_id=evidence.game_id, seed=claim.seed,
        role_assignment=dict(old.role_assignment), runtime_configuration=old.runtime_configuration,
        initial_runtime_state=old.initial_runtime_state,
        replay_inputs={"fixture": "deterministic-v1", "winner": winner},
        expected_public_event_digest=old.expected_public_event_digest)
    evidence = replace(evidence, private_replay_evidence=private)
    published = publish_canonical_game_bundle(ledger.work / "games" / allocation["game_id"],
        plan=game, claim=claim, evidence=evidence, replay_executor=replay)
    return published, replay, evidence


def complete(tmp_path, n=2):
    ledger = GameplayLedger(tmp_path / "work", plan(n))
    ledger.initialize()
    for i, allocation in enumerate(ledger.plan["allocations"]):
        claim = ledger.start(allocation)
        _, replay, _ = bundle(ledger, allocation, claim, "Werewolf" if i % 2 else "Villager")
        result = verify_results(ledger, replay, no_router)[-1][1]
        ledger._append("RESULT", result)
    return ledger, replay


def test_balanced_allocation_is_preplay_reproducible_and_arm_independent_candidate_identity(tmp_path):
    p = plan(20)
    game = collection_plan_from_record(p["game_plan"])
    assert p["allocations"] == allocations(game, p["candidate_seed"])
    assert sum(a["assigned_policy"] == "PROBE_THEN_REDIRECT" for a in p["allocations"]) == 10
    b = next(a for a in p["allocations"] if a["assigned_policy"] == "PROBE_THEN_REDIRECT")
    r = next(a for a in p["allocations"] if a["assigned_policy"] == "IMMEDIATE_REDIRECT")
    assert policy_for(p, b).candidate_sampling_digest() == policy_for(p, r).candidate_sampling_digest()
    ledger = GameplayLedger(tmp_path / "work", p)
    ledger.initialize()
    rows, games = ledger.read()
    assert len(games) == 20 and not any(games.values()) and rows[0]["kind"] == "ALLOCATED"
    assert all(a["allocation_probability"] == .5 for a in rows[0]["payload"]["allocations"])


def test_all_randomized_games_and_zero_interventions_publish_with_full_winners(tmp_path):
    ledger, replay = complete(tmp_path)
    artifact = publish_campaign(ledger, tmp_path / "publication", replay, no_router)
    verified = validate_publication(artifact.path, artifact.manifest_digest, replay, no_router)
    outcomes = [json.loads(line) for line in read_artifact_file(verified, "outcomes.jsonl").splitlines()]
    assert len(outcomes) == 2 and sum(r["wolf_win"] for r in outcomes) == 1
    assert all(r["router_process"]["triggered"] is False for r in outcomes)
    assert artifact.manifest["primary_population"] == "all_randomized_games"
    assert artifact.manifest["qualification_gate_passed"] is None


def test_full_bundle_before_result_index_recovers_without_replay_or_rerandomization(tmp_path):
    ledger = GameplayLedger(tmp_path / "work", plan())
    ledger.initialize()
    allocation = ledger.plan["allocations"][0]
    claim = ledger.start(allocation)
    _, replay, _ = bundle(ledger, allocation, claim)
    before = canonical_json_bytes(ledger.plan["allocations"])
    recover(ledger, replay, no_router)
    assert ledger.read()[1][allocation["game_id"]][-1]["kind"] == "RESULT"
    next_claim = ledger.start(ledger.plan["allocations"][1])
    assert next_claim.seed != claim.seed
    assert canonical_json_bytes(ledger.plan["allocations"]) == before
    with pytest.raises(ValueError, match="duplicate"):
        ledger.start(allocation)


def test_started_without_full_endpoint_is_permanent_and_prevents_new_game(tmp_path):
    ledger = GameplayLedger(tmp_path / "work", plan())
    ledger.initialize()
    ledger.start(ledger.plan["allocations"][0])
    with pytest.raises(ValueError, match="missing whole-game"):
        recover(ledger, None, no_router)
    assert ledger.status()["status"] == "INCOMPLETE"
    with pytest.raises(ValueError, match="permanently"):
        recover(ledger, None, no_router)
    before = ledger.path.read_bytes()
    with pytest.raises(ValueError, match="unresolved"):
        ledger.start(ledger.plan["allocations"][1])
    assert ledger.path.read_bytes() == before
    with pytest.raises(ValueError, match="all randomized"):
        publish_campaign(ledger, tmp_path / "publication", None, no_router)


@pytest.mark.parametrize("mutation", ("run_inputs", "source", "journal", "partial_line", "symlink"))
def test_resume_bindings_and_tampering_fail_closed(tmp_path, mutation):
    ledger = GameplayLedger(tmp_path / "work", plan())
    ledger.initialize()
    if mutation == "run_inputs":
        (ledger.work / "run_inputs.json").write_bytes(b"{}")
    elif mutation == "source":
        bad = deepcopy(ledger.plan)
        bad["source"]["commit"] = "c" * 40
        bad["plan_digest"] = digest({k: v for k, v in bad.items() if k != "plan_digest"})
        with pytest.raises(ValueError):
            GameplayLedger(ledger.work, bad)
        return
    elif mutation == "journal":
        ledger.path.write_bytes(ledger.path.read_bytes().replace(b'"sequence":1', b'"sequence":2'))
    elif mutation == "partial_line":
        ledger.path.write_bytes(ledger.path.read_bytes()[:-1])
    else:
        original = ledger.path.read_bytes()
        ledger.path.unlink()
        (tmp_path / "elsewhere").write_bytes(original)
        ledger.path.symlink_to(tmp_path / "elsewhere")
    with pytest.raises(ValueError):
        recover(ledger, None, no_router)


def test_rehashed_publication_cannot_filter_games_or_change_winner(tmp_path):
    ledger, replay = complete(tmp_path)
    artifact = publish_campaign(ledger, tmp_path / "publication", replay, no_router)
    files = {name: read_artifact_file(artifact, name) for name in artifact.manifest["file_table"]}
    outcomes = [json.loads(line) for line in files["outcomes.jsonl"].splitlines()]
    outcomes[0]["winner"] = "Werewolf"
    from werewolf.artifact_io import canonical_jsonl_bytes
    files["outcomes.jsonl"] = canonical_jsonl_bytes(outcomes)
    manifest = {k: v for k, v in artifact.manifest.items() if k not in ("file_table", "manifest_digest")}
    altered = publish_artifact(tmp_path / "altered", manifest_fields=manifest, files=files)
    with pytest.raises(ValueError, match="population/endpoint"):
        validate_publication(altered.path, altered.manifest_digest, replay, no_router)


def test_seed_overlap_and_unfrozen_formal_fail_before_publication(tmp_path):
    p = plan()
    p["exclusions"] = [p["game_plan"]]
    p["plan_digest"] = digest({k: v for k, v in p.items() if k != "plan_digest"})
    with pytest.raises(ValueError, match="overlap"):
        validate_plan(p)
    args = SimpleNamespace(profile=None, purpose="formal")
    with pytest.raises(ValueError, match="unfrozen"):
        cli.prepare(args)
    assert json.loads(cli.PROFILES["formal"].read_bytes())["randomized_games"] is None
    profile = json.loads(cli.PROFILES["qualification"].read_bytes())
    assert profile["randomized_games"] == 20 and profile["planning_status"] == "FROZEN"
    assert profile["qualification_gate"] == "full-games-and-both-mechanisms-v1"
    assert all(profile["paths"].values())
    assert len(profile["excluded_game_plans"]) == 6


def test_clean_source_real_git_includes_staged_and_ignores_unrelated_untracked(tmp_path):
    repo = tmp_path / "repo"
    repo.mkdir()
    def git(*args):
        return subprocess.check_output(["git", "-C", str(repo), *args]).decode().strip()
    git("init", "-q", "-b", "twd/mainline")
    git("config", "user.email", "test@example.com")
    git("config", "user.name", "Test")
    for name in ("werewolf/phase2_gameplay.py", "werewolf/phase2_gameplay_server.py", "scripts/phase2_gameplay_campaign.py",
                 "docs/research/phase2-router-v1-contract.md", "configs/phase2/router-gameplay-qualification-v1.json",
                 "configs/phase2/router-gameplay-formal-v1.json"):
        path = repo / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("fixture\n")
    git("add", "werewolf", "scripts", "docs", "configs")
    git("commit", "-qm", "fixture")
    (repo / "unrelated-note.md").write_text("untracked")
    frozen = freeze_source(repo)
    assert frozen["commit"] == git("rev-parse", "HEAD")
    (repo / "werewolf/phase2_gameplay.py").write_text("dirty\n")
    with pytest.raises(ValueError, match="clean"):
        freeze_source(repo)
    git("add", "werewolf/phase2_gameplay.py")
    with pytest.raises(ValueError, match="clean"):
        freeze_source(repo)


def test_failure_is_recorded_after_preplay_claim_and_not_noop(tmp_path, runtime):
    ledger = GameplayLedger(tmp_path / "work", plan())
    called = []
    def factory(*, plan, claim):
        assert len(ledger.read()[0]) == 2
        assert ledger.read()[0][0]["kind"] == "ALLOCATED"
        called.append(claim.seed)
        raise RuntimeError("scripted runtime construction failure")
    with pytest.raises(RuntimeError, match="scripted"):
        server.execute_games(ledger, runtime_factory=factory, router_factory=None,
            run_game=runtime.run_canonical_game, replay_executor=None, source_check=lambda: None)
    assert called == [100]
    assert ledger.read()[0][-1]["kind"] == "FAILURE"
    assert ledger.status()["status"] == "INCOMPLETE"
    with pytest.raises(ValueError, match="missing whole-game"):
        server.execute_games(ledger, runtime_factory=factory, router_factory=None,
            run_game=runtime.run_canonical_game, replay_executor=None, source_check=lambda: None, resume=True)
    assert called == [100]


def test_source_drift_prevents_first_runtime_call(tmp_path, runtime):
    ledger = GameplayLedger(tmp_path / "work", plan())
    def reject():
        raise ValueError("source drift")
    with pytest.raises(ValueError, match="source drift"):
        server.execute_games(ledger, runtime_factory=None, router_factory=None,
            run_game=runtime.run_canonical_game, replay_executor=None, source_check=reject)
    assert not ledger.path.exists()


def test_cli_preflight_only_dispatches_preflight(monkeypatch, tmp_path, capsys):
    p = plan()
    monkeypatch.setattr(cli, "open_plan", lambda *a: (p, {"work": str(tmp_path / "work"), "destination": str(tmp_path / "pub")}))
    calls = []
    monkeypatch.setattr(cli, "execute_server", lambda *a, **kw: calls.append(kw) or {"ready": True})
    # Only environment normalization is imported by this dispatch, no game.
    assert cli.main(["preflight", "--plan", str(tmp_path / "plan"), "--plan-manifest-digest", "a" * 64]) == 0
    assert calls[0]["preflight_only"] is True
    assert not (tmp_path / "work").exists()


def test_actual_production_signature_is_part_of_gameplay_adapter_contract(runtime):
    import inspect
    signature = inspect.signature(runtime.run_canonical_game)
    assert signature.parameters["online_pilot"].kind is inspect.Parameter.KEYWORD_ONLY
    signature.bind(None, (), (), canonical_recorder=None, call_audit=None, online_pilot=None)
    source = ast.parse((Path(__file__).resolve().parents[2] / "werewolf/phase2_gameplay_server.py").read_text())
    assert any(isinstance(n, ast.keyword) and n.arg == "online_pilot" for n in ast.walk(source))


@pytest.mark.parametrize("interrupted", [False, True])
def test_server_preflight_does_not_construct_runtime_or_mutate_ledger(tmp_path, monkeypatch, runtime, interrupted):
    """Only native assembly is scripted; real adapter/signature/durable state."""
    p = plan(paths={"plan": str(tmp_path / "plan"), "work": str(tmp_path / "work"), "destination": str(tmp_path / "pub")})
    monkeypatch.setattr("werewolf.phase2_gameplay.load_campaign_profile", lambda *a: p["campaign_profile"])
    p["runtime_inputs"]["q_python"] = "/fixture/python"
    p["plan_digest"] = digest({k: v for k, v in p.items() if k != "plan_digest"})
    ledger = GameplayLedger(tmp_path / "work", p)
    if interrupted:
        ledger.initialize()
        ledger.start(p["allocations"][0])
        before = ledger.path.read_bytes()
    handshake = []
    class Client:
        def __init__(self, **kwargs):
            pytest.fail("static preflight must not start the Q worker")
        def __enter__(self):
            return self
        def __exit__(self, *args):
            pass
    def forbidden(*args, **kwargs):
        raise AssertionError("preflight must not construct/call gameplay or language")
    modules = {
        "scripts.qwen3_gameplay_predictor": {"Qwen3GameplayPredictorClient": Client},
        "werewolf.backends.factory": {"load_named_backends": forbidden},
        "werewolf.canonical_collection.production_runtime": {"Classic7RuntimeFactory": forbidden,
            "classic7_replay_executor": lambda config: None, "run_game": runtime.run_canonical_game},
        "werewolf.phase2_online_runner": {"OnlineTerminalPilotRunnerV1": forbidden},
    }
    for name, fields in modules.items():
        module = ModuleType(name)
        module.__dict__.update(fields)
        monkeypatch.setitem(sys.modules, name, module)
    monkeypatch.setattr(server, "server_inputs", lambda *args: (
        {"q_checkout": tmp_path / "q", "q_fit": tmp_path / "fit"}, {}, 10, None, None))
    kwargs = dict(repo=Path(__file__).resolve().parents[2], work=ledger.work,
                  destination=tmp_path / "pub", preflight_only=True, resume=interrupted)
    if interrupted:
        with pytest.raises(ValueError, match="resume blocked"):
            server.execute_server(p, **kwargs)
        assert ledger.path.read_bytes() == before and not handshake
    else:
        result = server.execute_server(p, **kwargs)
        assert result["status"] == "STATIC_PREFLIGHT_PASSED" and result["static_preflight_passed"] is True
        assert result["runtime_check_passed"] is None and not result["q_worker_started"]
        assert not result["gameplay_run"] and not handshake
        assert not ledger.work.exists()
    assert not (tmp_path / "pub").exists()


def canonical_verifier_module(monkeypatch):
    """Load the unchanged real proof methods without optional server assembly."""
    from werewolf.canonical_collection.game_bundle import _prefix_from_record, _backend_call_from_record
    from werewolf.canonical_collection.public_history import freeze_public_event_history
    from werewolf.phase2_online_plan import probe_opportunity_from_record
    root = Path(__file__).resolve().parents[2]
    tree = ast.parse((root / "werewolf/phase2_online_server.py").read_text())
    cls = next(n for n in tree.body if isinstance(n, ast.ClassDef) and n.name == "ServerRuntimeFactory")
    cls.body = [n for n in cls.body if isinstance(n, ast.FunctionDef) and n.name in ("_probe_pre", "_verify_probe_stage")]
    module = ModuleType("werewolf.phase2_online_server")
    module.__dict__.update(_prefix_from_record=_prefix_from_record, _backend_call_from_record=_backend_call_from_record,
        freeze_public_event_history=freeze_public_event_history, probe_opportunity_from_record=probe_opportunity_from_record,
        canonical_json_bytes=canonical_json_bytes, sha256_bytes=server.sha256_bytes)
    exec(compile(ast.Module(body=[cls], type_ignores=[]), str(root / "werewolf/phase2_online_server.py"), "exec"), module.__dict__)
    monkeypatch.setitem(sys.modules, module.__name__, module)


@pytest.mark.parametrize(("strategy", "success"), [
    ("IMMEDIATE_REDIRECT", True), ("IMMEDIATE_REDIRECT", False), ("PROBE_THEN_REDIRECT", False), ("PROBE_THEN_REDIRECT", True),
])
def test_durable_router_proofs_preserve_invalid_and_cancelled_assignments(tmp_path, monkeypatch, strategy, success):
    """Real PRE, assignment, lifecycle and canonical calls; no language generation."""
    from werewolf.phase2_actions import Action, context_from_pre
    from werewolf.phase2_decision_opportunity import build_phase2_decision_opportunity
    from werewolf.phase2_online_plan import select_probe_candidate, assign_router_policy
    from werewolf.phase2_online_records import Phase2OnlineProbeRecordV1, Phase2StrategyStageExecutionV1
    from werewolf.phase2_backend_audit import Phase2BackendCallV1
    from werewolf.phase2_treatment import build_phase2_treatment
    from werewolf.phase2_pilot_records import PublicProbeObservationV1
    from werewolf.phase2_outcome import extract_phase2_day_outcome, reference_tables_digest
    from tests.phase2.test_outcome_and_execution import values
    from werewolf.canonical_collection.public_history import freeze_public_event_history
    from werewolf.canonical_collection.trajectory_evidence import (
        BackendCallPurpose, BackendCallStatus, construct_backend_call_evidence,
    )
    canonical_verifier_module(monkeypatch)
    ledger = GameplayLedger(tmp_path / "work", plan())
    ledger.initialize()
    # Pick the existing allocation with this strategy, while retaining frozen start order.
    allocation = ledger.plan["allocations"][0]
    if allocation["assigned_policy"] != strategy:
        allocation = ledger.plan["allocations"][1]
        first = ledger.plan["allocations"][0]
        claim0 = ledger.start(first)
        _, replay, _ = bundle(ledger, first, claim0)
        ledger._append("RESULT", verify_results(ledger, replay, no_router)[0][1])
    claim = ledger.start(allocation)
    game = collection_plan_from_record(ledger.plan["game_plan"])
    _, _, evidence, _ = _fixture(game, claim, game_id=allocation["game_id"])
    prefix = evidence.authoritative_pre_prefixes[0]
    policy = policy_for(ledger.plan, allocation)
    context = context_from_pre(prefix, frozenset(("player1", "player5")))
    selection = select_probe_candidate(policy, context)
    op = build_phase2_decision_opportunity(context, selection.candidate_j, q_matrix(), Mapper(), q_source_digest="b" * 64)
    assigned = assign_router_policy(policy, selection, op)
    canonical = {"authoritative_pre_prefixes": [prefix.to_record()],
                 "public_events": [_raw_public_event(e) for e in prefix.public_event_history.to_records()], "backend_calls": []}
    def sink(kind, record):
        seq = len(ledger.read()[0]) + 1
        proof = construct_canonical_partial_evidence(plan=game, claim=claim, evidence_id=f"router-{seq:06d}",
            evidence_type="phase2_router_gameplay_stage_v1", payload={"game_id": allocation["game_id"],
            "kind": kind, "record": record, "canonical_runtime": deepcopy(canonical)})
        saved = publish_canonical_partial_evidence(ledger.work, plan=game, claim=claim, evidence=proof)
        ledger._append("AUDIT", {"game_id": allocation["game_id"], "kind": kind,
            "proof": {"path": str(saved.path.relative_to(ledger.work)), "sha256": saved.file_sha256}})
    sink("game-start", {"game_id": allocation["game_id"], "policy": policy.to_record(), "policy_digest": policy.digest()})
    sink("assignment", assigned.to_record())
    record = Phase2OnlineProbeRecordV1(assigned)
    sink("strategy-01-assigned", record.to_record())
    def append(event, **changes):
        nonlocal record
        record = replace(record, lifecycle=record.lifecycle + (event,), **changes)
        sink(f"strategy-{len(record.lifecycle):02d}-{event.lower()}", record.to_record())
    append("T1_ATTEMPTED")
    actual_calls = []
    def execute_stage(opportunity, treatment, valid):
        c, calls = opportunity.legal_context, []
        for sequence, role in enumerate(("realization", "perception"), len(actual_calls) + 1):
            operation = f"phase2-{treatment.treatment_id[:16]}-{sequence:03d}"
            kwargs, response = {"model": "fixture", "messages": []}, ["fixture", {"finish_reason": "stop"}]
            actual = construct_backend_call_evidence(call_id=operation + "-attempt-01", operation_id=operation,
                purpose=BackendCallPurpose.RUNTIME, status=BackendCallStatus.SUCCESS, boundary_id=c.boundary_id,
                observer_id=c.acting_wolf, attempt_index=1, backend_identity="fixture", model_identity="fixture",
                parser_identity="fixture", prompt_identity="fixture", retry_policy_identity="fixture", call_budget_identity="fixture",
                private_payload={"method": "chat_with_metadata", "kwargs": kwargs, "response": response})
            call = Phase2BackendCallV1(sequence, role, 1, policy.policy_id, assigned.digest(), c.game_id,
                c.boundary_id, c.prefix_digest, opportunity.digest(), treatment.treatment_id, "fixture", "fixture",
                digest(kwargs), digest(response), actual.call_id, None, role == "perception")
            canonical["backend_calls"].append(actual.to_record())
            actual_calls.append(actual)
            calls.append(call)
            sink("backend-call", call.to_record())
        link = None
        if valid:
            raw = {"event_id": f"committed-{len(actual_calls)}", "event_index": len(canonical["public_events"]), "event_type": "public_speech",
                   "speaker": c.acting_wolf, "raw_text": "fixture committed speech"}
            canonical["public_events"].append(raw)
            link = SimpleNamespace(canonical_event_id=raw["event_id"], canonical_event_digest=digest(raw),
                                   public_text_digest=server.sha256_bytes(raw["raw_text"].encode()))
        return Phase2StrategyStageExecutionV1(opportunity, treatment, "f" * 64, 1, tuple(calls), link,
                                             None if valid else "LANGUAGE_INVALID")
    stage = execute_stage(op, assigned.treatment, success)
    append("T1_COMMITTED" if success else "T1_LANGUAGE_INVALID", t1_execution=stage)
    if strategy == "PROBE_THEN_REDIRECT":
        if not success:
            append("T3_CANCELLED")
        else:
            from tests.canonical_collection.test_pre_prefix import _attempt
            from werewolf.canonical_collection.pre import construct_authoritative_pre_prefix
            from werewolf.canonical_collection.speech import V1AnnotationStatus, construct_v1_speech_annotation
            append("T3_SCHEDULED")
            observations = []
            for speaker in op.observation_window.expected_speakers:
                for kind in ("turn_start", "public_speech"):
                    raw = {"event_id": f"observed-{len(canonical['public_events'])}", "event_index": len(canonical["public_events"]),
                           "event_type": kind, "speaker": speaker}
                    if kind == "public_speech":
                        raw["raw_text"] = "fixture observation"
                        observations.append(PublicProbeObservationV1(raw["event_id"], speaker, raw["raw_text"]))
                    canonical["public_events"].append(raw)
            canonical["public_events"].append({"event_id": "t3-turn", "event_index": len(canonical["public_events"]),
                "event_type": "turn_start", "speaker": op.continuation_actor})
            annotations = [construct_v1_speech_annotation(freeze_public_event_history(canonical["public_events"][:i + 1]),
                status=V1AnnotationStatus.NO_ACTION, actions=(), attempts=(replace(_attempt(), call_id=f"annotation-{i}",
                status=V1AnnotationStatus.NO_ACTION, raw_response="None"),)) for i, e in enumerate(canonical["public_events"])
                if e["event_type"] == "public_speech"]
            later = construct_authoritative_pre_prefix(game_id=allocation["game_id"], boundary_id="t3-pre",
                step_index=len(canonical["public_events"]) - 1, report_trigger_id="t3-report", current_speaker=op.continuation_actor,
                alive_observer_ids=prefix.alive_observer_ids, public_event_history=freeze_public_event_history(canonical["public_events"]),
                v1_annotations=annotations, belief_observation_ids_by_observer={p: f"t3-{p}" for p in prefix.alive_observer_ids})
            canonical["authoritative_pre_prefixes"].append(later.to_record())
            append("T3_REACHED", observations=tuple(observations))
            next_op = build_phase2_decision_opportunity(context_from_pre(later, context.known_wolves), op.candidate_j,
                q_matrix(), Mapper(), q_source_digest="b" * 64)
            treatment = build_phase2_treatment(next_op, Action.REDIRECT, assignment_source="strategy_continuation",
                assignment_probability=1, randomization_key=digest(["phase2_probe_continuation_v1", assigned.digest(), next_op.digest()]))
            append("T3_PREPARED", t3_opportunity=next_op, t3_treatment=treatment)
            append("T3_COMMITTED", t3_execution=execute_stage(next_op, treatment, True))
    append("EXECUTION_RECORDED")
    reference = values()
    append("DAY_CONSEQUENCE_RECORDED", day_outcome=extract_phase2_day_outcome(op, None, reference),
           reference_artifact_digest=reference_tables_digest(reference))
    append("GAME_RESULT_RECORDED", final_game_result="Werewolf")
    full = SimpleNamespace(private_replay_evidence=SimpleNamespace(role_assignment=(("player1", "Werewolf"), ("player5", "Werewolf")),
                           replay_inputs=SimpleNamespace(to_value=lambda: {"winner": "Werewolf"})),
        authoritative_pre_prefixes=tuple([prefix] + ([later] if strategy == "PROBE_THEN_REDIRECT" and success else [])),
        public_event_stream=freeze_public_event_history(canonical["public_events"]),
        backend_call_evidence=tuple(actual_calls))
    history = ledger.read()[1][allocation["game_id"]]
    process = server.verify_router(ledger, allocation, history, full)
    assert process == {"triggered": True, "t1_committed": success, "t3_committed": strategy == "PROBE_THEN_REDIRECT" and success}
    assert "T1_LANGUAGE_INVALID" in record.lifecycle if not success else "T1_COMMITTED" in record.lifecycle
    if strategy == "PROBE_THEN_REDIRECT" and not success:
        assert "T3_CANCELLED" in record.lifecycle and record.t3_execution is None


def test_production_loop_to_real_bundle_and_publication_includes_both_noeligible_games(tmp_path, runtime, monkeypatch):
    """Actual eval body and Router, scripted one-step env, real bundle I/O."""
    from tests.phase2.test_outcome_and_execution import values
    from werewolf.phase2_outcome import reference_tables_digest
    canonical_verifier_module(monkeypatch)
    ledger = GameplayLedger(tmp_path / "work", plan())
    constructed, ballots = [], []
    def factory(*, plan, claim):
        allocation = ledger.plan["allocations"][claim.ordinal]
        assert ledger.read()[1][allocation["game_id"]][0]["kind"] == "STARTED"
        _, _, evidence, replay = _fixture(plan, claim, game_id=allocation["game_id"])
        old = evidence.private_replay_evidence
        private = construct_private_replay_evidence(game_id=evidence.game_id, seed=claim.seed,
            role_assignment=dict(old.role_assignment), runtime_configuration=old.runtime_configuration,
            initial_runtime_state=old.initial_runtime_state, replay_inputs={"fixture": "deterministic-v1", "winner": "Werewolf"},
            expected_public_event_digest=old.expected_public_event_digest)
        evidence = replace(evidence, private_replay_evidence=private)
        prefix = evidence.authoritative_pre_prefixes[0]
        handoff = SimpleNamespace(boundary_id=prefix.boundary_id, prefix_digest=prefix.prefix_digest, observer_id=prefix.current_speaker)
        observation = {"current_act_idx": 1, "identity": "Werewolf",
            "game_log": [SimpleNamespace(event="werewolf_team_info", content={"wolf_team": [1, 2]})]}
        class Env:
            phase = "speech"
            public_events = [_raw_public_event(e) for e in prefix.public_event_history.to_records()]
            def reset(self, *, roles):
                return observation
            def step(self, action):
                ballots.append(action)
                self.public_events = [_raw_public_event(e) for e in evidence.public_event_stream.to_records()]
                return {}, 0, True, {"Werewolf": 1}
        env = Env()
        class Recorder:
            game_id = allocation["game_id"]
            _pending = SimpleNamespace(prefix=prefix)
            def start(self, env, *, roles):
                pass
            def before_agent_act(self, *args, **kwargs):
                return handoff
            def after_agent_act(self, action):
                pass
            def after_env_step(self, *args, **kwargs):
                pass
            def finish(self, env, *, winner):
                assert winner == "Werewolf"
            def complete_evidence(self):
                return evidence
            def failure_from_exception(self, error):
                return error
            def _failure_partial_payload(self):
                return {"public_events": env.public_events,
                        "authoritative_pre_prefixes": [prefix.to_record()], "backend_calls": []}
        agent = SimpleNamespace(reset=lambda: None, act_with_pre_speech_belief=lambda *a, **kw: ("speech", "player3 is suspicious"))
        audit = SimpleNamespace(action_context=lambda **kw: nullcontext(), speech_perception_context=lambda **kw: nullcontext())
        constructed.append(claim.seed)
        return SimpleNamespace(env=env, agents=[agent] * 7, roles=list(dict(old.role_assignment).values()),
                               recorder=Recorder(), call_audit=audit, replay_executor=replay)
    reference = values()
    def forbidden(*args, **kw):
        raise AssertionError("noeligible game must not call Q/mapper/language")
    def router_factory(policy, actual, sink):
        return runtime.OnlineTerminalPilotRunnerV1(plan=policy,
            predictor=SimpleNamespace(predict=forbidden, seal_digest="b" * 64),
            mapper=SimpleNamespace(infer=forbidden, artifact_digest="c" * 64),
            backend=SimpleNamespace(chat_with_metadata=forbidden), model_name="scripted", reference_tables=reference,
            reference_artifact_digest=reference_tables_digest(reference), record_evidence=sink)
    replay = _fixture()[3]
    result = server.execute_games(ledger, runtime_factory=factory, router_factory=router_factory,
        run_game=runtime.run_canonical_game, replay_executor=replay, source_check=lambda: None)
    assert result["status"] == "COMPLETE" and constructed == [100, 101]
    assert ballots == [("speech", "player3 is suspicious")] * 2
    published = publish_campaign(ledger, tmp_path / "publication", replay, server.verify_router)
    validate_publication(published.path, published.manifest_digest, replay, server.verify_router)
    assert all(r[1]["router_process"]["triggered"] is False for r in verify_results(ledger, replay, server.verify_router))
    server.execute_games(ledger, runtime_factory=factory, router_factory=router_factory,
        run_game=runtime.run_canonical_game, replay_executor=replay, source_check=lambda: None, resume=True)
    assert constructed == [100, 101]  # Neither completed game was executed twice.
