name: untrusted-network-simulation-vllm
channels:
  - conda-forge
  - nodefaults
variables:
  PYTHONNOUSERSITE: "1"
  CUDA_HOME: "/data/yuxiao/envs/untrusted-network-simulation-vllm/lib/python3.12/site-packages/nvidia/cu13"
dependencies:
  - python=3.12
  - pip
  - pip:
      - vllm==0.27.0
